# Generated by Django 5.1.1 on 2024-12-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_application_ta_applicant_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ta_applicant_response',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
